### PR TITLE
Bind error codes to error variants

### PR DESCRIPTION
**Pull request by Robert-Steiner**
small follow up PR based on https://github.com/xaynetwork/xaynet/pull/538#discussion_r500269333

### CODE REVIEW

**Review by finiteprods — COMMENTED** [review]
this looks nice, thanks for trying it out. It's good to have the error codes defined together with the error variants, and there's even a modest saving in LoC (more than I was expecting with this `num_enum` crate, nice find!). Looks very promising to me. :1st_place_medal:

**Review by little-dude — APPROVED** [review]
This would be nice to have yes. I initially thought we didn't need `num_enum` since we can already [explicitely choose an enum discriminant](https://doc.rust-lang.org/reference/items/enumerations.html#custom-discriminant-values-for-fieldless-enumerations). However this only gives us the enum -> integer conversion, while we also need the integer -> enum one. `num_enum` provides that.

**Review by janpetschexain — APPROVED** [review]

**Review by finiteprods — COMMENTED** [review]
looks great. one minor comment: I notice sometimes `0` represents OK, negative numbers are errors. other times, `1` is OK and `0` is error. should we settle on a convention?

**Comment by Robert-Steiner** [comment]
I agree, that would make it more consistent but then I have to add code that converts the numbers because I in this case simply use the return values ​​of the redis commands.

e.g. in the `add_sum_participant` the return values comes from `hset_nx`

https://github.com/xaynetwork/xaynet/blob/6eec7ec2f4b9a9520bf59257c0e4176442c7d895/rust/xaynet-server/src/storage/redis.rs#L160-L179

**Comment by finiteprods** [comment]
> I agree, that would make it more consistent but then I have to add code that converts the numbers because I in this case simply use the return values ​​of the redis commands.

Ah, ok. Yep, makes sense to keep it as it is then.

**Pull request merged**
