### PR TITLE
Release v0.9.0

### PR DESCRIPTION
**Pull request by rsaffi**
Outcome of running `scripts/bump_version.sh -m`.

### CODE REVIEW

**Comment by rsaffi** [comment]
I could use some help with the `CHANGELOG.md`, actually... :thinking:

**Comment by Robert-Steiner** [comment]
For the change log maybe

```
This release introduces the integration of the [PET protocol](https://www.xain.io/assets/XAIN-Whitepaper.pdf) into the platform.

**Note:**
The integration of the PET protocol required a complete rewrite of the codebase and is therefore not compatible with the previous release.
```
?

**Comment by rsaffi** [comment]
> For the change log maybe
> 
> ```
> This release introduces the integration of the [PET protocol](https://www.xain.io/assets/XAIN-Whitepaper.pdf) into the platform.
> 
> **Note:**
> The integration of the PET protocol required a complete rewrite of the codebase and is therefore not compatible with the previous release.
> ```
> 
> ?

LGTM. Would you like to suggest the change and Co-author this PR or should I apply that myself?

**Comment by Robert-Steiner** [comment]
Feel free to add this yourself

**Comment by rsaffi** [comment]
PR updated with changes to the CHANGELOG.

**Pull request merged**
